### PR TITLE
Fixed most warnings. Added CMakeLists.txt.

### PR DESCRIPTION
**Pull request by lpolasek**

### CODE REVIEW

**Comment by xLAva** [comment]
Thx again for your work.
I'll have a look at it on Friday (I'm busy tomorrow) and today the bug hunting was more important.

**Comment by lpolasek** [comment]
You are welcome, I found a problem when I play the game, I will fix it soon. It seems related to a bad compilation :(

Best regards...

**Comment by lpolasek** [comment]
I have cleared up CMakeLists.txt, and now it compiles a working version of jk2sp :)
Keep me updated of any problem.

**Comment by xLAva** [comment]
Thx again for your commit.
I checked your code and it looks good to me.

I don't have much time today, so I'll build a new binary tomorrow when I have time to do a proper test with it.

**Comment by lpolasek** [comment]
Ok, excellent, tell me if you find any issue.

Best regards...

**Pull request merged**
