### PR TITLE
Fix CTRL key breaking controls.

### PR DESCRIPTION
**Pull request by pudiva**

### CODE REVIEW

**Comment by xLAva** [comment]
Hi!
Thx for the pull request. This issue is very interesting.
Sadly your added link in the code does not work at the moment. 

And I thing it would be better to add a button mask check for the control key before doing the additional key calculation you added.

What to you think?

**Comment by pudiva** [comment]
EHLO!

Sorry for being so dry on my pull request. Sad it is, indeed =o(, but I thought
it would be even more to strip it from it's fix! Anyway, I borrowed this from
Quake3 sauce, to fix ctrl rendering other keys useless while pressed.

Teh patch works teh way it is, but introduces another bug: sometimes pressing
ctrl (my crouch key) and space (my jump key) simultaneously would swap teh
functions until I pressed each key independently. This is less annoying than
having keys unusable while crouching and I could finish teh game on Jedi Master
without getting REALLY mad =o3.

Perhaps this button mask thing is teh bit I missed from Quake3. In fact, I was
hoping to just copy teh entire file over, but your sauce has many differences!
I will think a little about it when I wake up, I'm very tired now.

Thank you for this port! <3

**Comment by xLAva** [comment]
I integrated your fix and I found why the space key was not working and fixed it as well.
I will build a new binary sometime next week.

**Comment by pudiva** [comment]
Thank you very much! <3

## 

Igor

**Pull request merged**
