### PR TITLE
Vive/OpenVR support

### PR DESCRIPTION
**Pull request by shinyquagsire23**
Got a Vive so I went ahead and ported things over to OpenVR, things seem to be working fine so far, though menus could use a bit of work. Ran into a strange issue with RE_StretchDraw though, while OpenVR is active and doing its thing the qglTexSubImage2D used there causes the game to crash, couldn't sort out why but it only breaks the opening cinematic for now so I #ifdef'd it out for OpenVR builds.

Also added `cg_debugHmdHands`, gives a nice display of both hands. Was hoping to adjust gun positions but they're all over the place. Will probably keep them around though, I'd like to map more things to hand positions and knowing both hand locations will be helpful.

Also just another note, but the scaling feels off for some reason, but I can't quite put my finger on it. The chaperone floor doesn't ever feel like it matches the game's floor, ends up feeling like I'm in a floating box when the chaperone comes up. I almost wonder if, despite position and such being scaled into the engine, that everything will need to be scaled down when it's time to render, dunno. Otherwise everything feels OK, though.

### CODE REVIEW

**Comment by TheWolfaw** [comment]
Hi. I have a vive too and i would love to play this game with my vive.

As a nonprogrammer, is there any chance to start your new code or is a new release the only way to play it?

so if i understand this website correct. the code is open source and you added/changed something for vive support and i would need to download this project and your changed code and could play it with an c++ interpreter? Would be nice if you could say some quick steps how vive play could be possible for everyone :)

good work and thank you :+1:

**Comment by xLAva** [comment]
This is great news!
I'm not home this weekend, but I will pull it next week and build a new release version with the vive support.

Thx for your work and for sharing it!

**Comment by TheWolfaw** [comment]
@xLAva 
is it possible to get a on / off switch for the motion controller support in the next release? i know that it is in a beta stage but the possibility to test it would be awesome!

**Comment by shinyquagsire23** [comment]
@TheWolfaw controllers are toggled with `hmd_useHands` on VR-Touch

~~Also I do want to throw this in here, but just projecting some issues I've personally run into with the Vive wands, perhaps it would be a good idea to move all of the ClientHmd and GameHmd angles from euler to quaternion? Or perhaps just the matrix directly? At least right now if I try and hold the Vive wand up vertically it starts to freak out a bit, and most of the calculations used w/ the angles just throw them into AnglesToAxis anyhow, and the parts where euler angles are actually used directly could have conversion moved outside of the client code. Going to at least experiment with moving things in that direction, perhaps for another PR.~~

Never mind, fixed the inconsistencies w/ controller rotation.

EDIT 2: Saber was still broke, I could not for the life of me figure out why adding 45 degrees wouldn't work, but it didn't. Had a TODO to move the grip orientation into IHmdDevice so I did that, working fine on Vive now: https://www.youtube.com/watch?v=rlKGKDty1ic

**Comment by TheWolfaw** [comment]
@xLAva 
i cant wait for the vive release!
I testet to compile it with visual studio but it doenst work for me, but i think i am just to dumb^^

Only a .exe file to start would be great :)
you would be my hero if you would make a release before saturday because than i get visited from a longdistant friend and he was a huge jedi knight fan to. He would love to see it in VR.

Thank you!

**Comment by xLAva** [comment]
@TheWolfaw 
I will try to create one on Friday night. So if everything goes well it should be ready for Saturday morning.

**Comment by xLAva** [comment]
@shinyquagsire23 
I just merged your changes into VR-Touch - everything looked really good.
Thx for all your work! 

I just made your tempfix a bit more dynamic. Now it is only active if a OpenVR device is actually used (please check if this actually works if you got time).
And you had a small compile error in the Oculus part which I fixed (no big deal).

**Comment by xLAva** [comment]
@TheWolfaw 
I did build a new Windows binary.
It is of course very experimental.
Just download all the files in here: https://github.com/xLAva/JediOutcastLinux/tree/VR-Touch/binary/win32

I did not create a new release yet (in the github release section).
It is too early for that. We have to fix some more bugs before a new major release.

**Comment by TheWolfaw** [comment]
Thank you!

I will check it out today as soon as i can :+1:

**Pull request merged**
