### PR TITLE
Fix to Issue 'game crashes on bespin_platform boss fight'.

### PR DESCRIPTION
**Pull request by lpolasek**
This was causes by a 'Division by 0 on Q_irand

### CODE REVIEW

**Comment by xLAva** [comment]
I already explained my fix in the other bug thread. :-)
Sorry I'm not more active at the moment - I'm having a cold and I'm lying sick at home.

**Comment by lpolasek** [comment]
No problem, hope you get well soon.

Best regards...

**Comment by lpolasek** [comment]
Can we solve more elegantly by:

return ((rand() / RAND_MAX) \* (max-min)) +min;

So we don't need the if clause. What do you think ?

Regards...

**Comment by xLAva** [comment]
I know that the if clause is not the most elegant solution.
But your suggestion won't work, because 
rand() / RAND_MAX 
is an int operation so it will always be zero.
and I think a int to float and back again conversion is more expensive then the ugly if clause.

**Comment by lpolasek** [comment]
Yes, you are right, seems that my head is not working 100% today :(
Sometimes I forget that I am dealing with integers.

Best regards...

**Pull request closed without merging**
