### PR TITLE
makefile added

### PR DESCRIPTION
**Pull request by jelly**
This adds a quick'n dirty makefile to the project. So people can contribute without having codeblocks installed

### CODE REVIEW

**Comment by demonixis** [comment]
Nice ! This is really usefull

**Comment by xLAva** [comment]
Wow - thx. Came out of the blue. I'll check it out on Friday. I'm busy until then.

**Comment by xLAva** [comment]
I think you forgot to add the jk2gamex86.so lib build in your makefile.
Please add this lib build.

And remove alut lib linking - we don't use it.
Thx.

**Comment by jelly** [comment]
Hi, I've removed linking to lib. I'm not sure how to add jk2gamex86.so to the makefile

**Comment by xLAva** [comment]
Thx for your effort, but I think with the CMake stuff in place we don't need manual makefiles any more.
If there is a reason to stick with it, write a comment.

I close this in the mean time.

**Pull request closed without merging**
