### PR TITLE
Track Weapon Position/Orientation to Right Hand

### PR DESCRIPTION
**Pull request by shinyquagsire23**
This PR is currently a WIP, allows weapons to track to any position/orientation. Currently it's set up with a static position and rotation, however no matter the position and orientation the weapon will always shoot in that direction.

As of now I kinda feel like controllers should be abstracted as their own device, but at the same time controllers are usually linked to the headset itself (ie with Oculus' CV1 the Touch Controllers communicate with the headset, same with the Vive as well I think).

Unfortunately I don't actually have a CV1 nor Touch controllers (just a DK2) so I can't actually validate whether Touch controllers will work once I tie their position/orientation to the gun. At the very least though the orientation worked when I just tied it to the HMD orientation, position I'm uncertain with though.

### CODE REVIEW

**Comment by xLAva** [comment]
Thx for the work!
At first glance it looks good to me.

I will give it a spin this evening after work.
Fortunately I have input controllers, so I will try to hook them up to your code.

**Comment by shinyquagsire23** [comment]
Was out of town for a bit, did some more testing and I think I'll have to bring in my decoupled aiming as well. Right now the weapon and crosshair follows the HMD which seems to be messing up the weapon tracking. I'll probably just set it up so that controllers default to decoupled aim and if someone wants decoupled aim with a mouse there'll be a client variable for it to be forced. But basically it allows the mouse to adjust the pitch/yaw of the aim without needing head movement, and for controllers the mouse/thumbsticks to be the only thing adjusting yaw.

The other issue is that having the gun able to move anywhere messes up the crosshair, the crosshair still follows the old aim but the gun still only follows the set position/rotation separate from the camera/view aim. Might try to fix that but the crosshair can also just be disabled for controllers I guess.

**Comment by shinyquagsire23** [comment]
OK decoupling the aim and then tying `position_r` and `angles_r` to `ClientHmd::GetPosition` and `ClientHmd::GetOrientation` seems to work now, I tried that before and the position got thrown off because the gun kept rotating and messing up my yaw math. I can even turn my head all the way around and shoot opposite to the direction I'm technically facing, which is neat.

I think I'll at least try tying in Oculus' hand positions for now since the HMD position is working as-is, can't test that though. From there it's probably some cleanup to keep things working without hands and allowing for hands to be disabled.

**Comment by shinyquagsire23** [comment]
OK I fixed the crosshair position, now it tracks separately from the view when the weapon is attached to hands. I also set my earlier modifications to work only with hands as well, apparently tracking to the actual weapon's barrel makes aiming incredibly hard with weapon bobbing. Can't test with Touch controllers but I'm going to try and find some people who can in the mean time since I'm curious if it all works.

**Comment by xLAva** [comment]
Sorry - I did not have time yet so look at the code. I hope I can do this on the weekend.
About the decoupling of view and aim: I thought I already prepared something for that (weapon view I think it was called), but I'm not sure. It was a long time ago and I don't know how deep I prepared stuff for it.

Thx for your work - I hope I can get a good look at it soon.

**Comment by shinyquagsire23** [comment]
OK so I got to talk with someone who actually had Touch controllers and it seems the big issues right now are,

- Touch controllers aren't really hooked into input
- Having to recenter the player's position while they're standing + the previous can be difficult, though I know SteamVR has a room calibration setup so that there's no recentering to deal with, no idea with Oculus though.
- ~~Rotation on the weapons is wrong, the weapons swing around some other point rather than rotating around its own origin~~

~~I'm going to at least try and get the last one situated since input and roomscale I can't really test that well.~~

Got the rotation sorted out, and I went ahead and removed the depth hacks on weapons where it would render the weapon in front of walls even if it was clipping through it, doesn't look too good in VR and especially with hands I think clipping is desirable for depth perception.

**Comment by xLAva** [comment]
I just had a look at your code.
Looks good to me.

Just small stuff I would like to change.
I will put the code in a new branch called VR-Input

**Comment by xLAva** [comment]
Done.
I made some quick changes.

I re-added the hmd_useHands value - so that the players can disable touch input (it is disabled by default right now until the feature is more finished)

I also changed the meter to game unit for position tracking - my original value just felt wrong.

**Comment by xLAva** [comment]
There are still issues with rotation - the weapon has an offset when rotating. 
It feels like the weapons are attached to an angled stick.

But position feels really good.
All in all good work - even more so, because you had to do it without touch input devices.

**Comment by xLAva** [comment]
FYI: I will try to hook up the buttons of the touch input devices to the game in the next couple of days.

**Pull request closed without merging**
