### PR TITLE
Fix weapons to follow weapon view yaw when tracked to hands.

### PR DESCRIPTION
**Pull request by shinyquagsire23**
Hopefully this should be just about everything that's kinda game-breaking as far as weapon tracking goes, I think what happened is that my code to compensate for yaw was just built on the same bad assumptions which made rotation borked before.

### CODE REVIEW

**Comment by xLAva** [comment]
I just tested it. 
The input yaw does not change the behavior of the weapon rotation or position which is very good.
But the position tracking is wrong.
Up and down works
Left and right is mirrored and does not feel correct. 
Also the rotation changes depending on how far left or right the position is. (the weapon always points in the middle).

I'm sorry that I did not have a proper look at your code to help out with fixing the issues. I just had time to do a quick test before I go to work.

I will merge it in anyway, so that we are on the same code base.

**Comment by shinyquagsire23** [comment]
Actually, with regard to the left and right being mirrored, can you check with a new savegame when you get the chance? I'm noticing in my saves I made while fixing the rotation and yaw it's flipped, but on my older saves I made before VR-Touch and on new saves it's correct (I think). I'm not sure why the behavior changes like that but it caused me some confusion where it was working for a while and then flipped for no reason.

And also I guess it's worth noting, I'm actually on break from school so I've had a lot of spare time personally. Totally understand the delay with testing and code review though.

EDIT: Actually, it seems to depend on the direction the save was saved in, so something's wrong I guess. I'm also noticing that when I save facing one direction, the direction I face when I load changes and the behavior of the position tracking changes with it. The correct code should be 
```
VectorMA(origin, -(vrRX * c - vrRY * s), viewaxisWeapon[0], origin);
VectorMA(origin, -(vrRX * s + vrRY * c), viewaxisWeapon[1], origin);
```
though, I think.

**Comment by xLAva** [comment]
With a new game it works normally.
Thx for checking for errors.
When it works, the position tracking looks very good.

I'm just not a huge fan of the player movement being not influenced by the VR rotation at all.
It is really hard to move around the level, if you always have to rotate with the controller to move correctly forward.

I know there are multiple preferences on this, but I like the mode, where the position movement is influenced by the viewing direction. It just works and as player you can go around the level very easy.

Was it your intention to decouple the player movement completely from VR direction change?
I totally understand why we can't base it on the direction of the weapon, but is there a reason to also decouple it from the VR headset rotation?

**Comment by shinyquagsire23** [comment]
Hm, I'm personally a fan of decoupled aiming and movement being linked to the mouse only from a seated standpoint. I originally introduced decoupled aiming for hands though because otherwise the position of the gun swings with your head, but I think I'm getting familiar enough with things that I could probably fix the weapon swing and still have view-based movement depending on hmd_decoupledAim.

**Pull request merged**
